/**
 * pwa.mjs — a tiny Astro integration that makes the static Starlight build
 * installable and fully offline-capable.
 *
 * It does one job: after the build completes, walk `dist/` and emit
 * `sw-manifest.js`, a versioned precache manifest consumed by `/sw.js`.
 * The version is a hash of the file list, so every deploy produces a new cache
 * name and the service worker purges the previous one on activation.
 */
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

/** Files worth precaching (HTML, CSS/JS, fonts, icons, search index shell). */
const PRECACHE_EXT = new Set([
	'.html',
	'.css',
	'.js',
	'.mjs',
	'.woff2',
	'.svg',
	'.png',
	'.webp',
	'.ico',
	'.webmanifest',
	'.json',
]);

/** Never precache the worker itself or the source maps. */
const SKIP = [/^\/sw\.js$/, /^\/sw-manifest\.js$/, /\.map$/, /^\/pagefind\/.*\.pf_/];

export function pwa({ offlinePage = '/offline.html' } = {}) {
	return {
		name: 'gap-atlas-pwa',
		hooks: {
			'astro:build:done': ({ dir, pages, logger }) => {
				const outDir = fileURLToPath(dir);
				const urls = new Set(['/']);

				// `pages` lists built routes; register both the file path and, for
				// directory indexes, the clean URL a navigation actually requests.
				for (const page of pages) {
					const rel = `/${String(page.pathname).replace(/^\/+/, '')}`;
					urls.add(rel);
					if (rel.endsWith('/index.html')) urls.add(rel.slice(0, -'index.html'.length));
				}

				const walk = (dirPath) => {
					for (const entry of fs.readdirSync(dirPath, { withFileTypes: true })) {
						const abs = path.join(dirPath, entry.name);
						if (entry.isDirectory()) {
							walk(abs);
							continue;
						}
						const rel = `/${path.relative(outDir, abs).split(path.sep).join('/')}`;
						if (!PRECACHE_EXT.has(path.extname(rel))) continue;
						if (SKIP.some((re) => re.test(rel))) continue;
						urls.add(rel);
					}
				};
				walk(outDir);

				const precache = [...urls].sort();
				if (!precache.includes(offlinePage)) precache.push(offlinePage);

				const bytes = precache.reduce((sum, url) => {
					const abs = path.join(outDir, url.replace(/^\//, ''));
					try {
						return sum + fs.statSync(abs).size;
					} catch {
						return sum;
					}
				}, 0);

				const version = crypto
					.createHash('sha1')
					.update(precache.join('|'))
					.digest('hex')
					.slice(0, 10);

				fs.writeFileSync(
					path.join(outDir, 'sw-manifest.js'),
					`/* generated by the gap-atlas-pwa integration — do not edit */\n` +
						`self.__GAP_ATLAS_MANIFEST = ${JSON.stringify(
							{ version, offlinePage, precache },
							null,
							'\t'
						)};\n`
				);

				logger.info(
					`PWA: ${precache.length} files precached (${(bytes / 1024 / 1024).toFixed(2)} MB), cache version ${version}`
				);
			},
		},
	};
}
